#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Only bump version on main branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  node scripts/bump-version.js
  git add package.json package-lock.json
fi
