name: beta deploy to github pages

on:
  push:
    branches:
      - beta
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pages: write

    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Persist npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build-ghpages

      - name: setup gh pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload just output folder
          path: './dist'

      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v4